### ISSUE TITLE
Clock and calendar in default conky?

### ISSUE THREAD

**Issue by johnraff** [BunsenLabs/bunsen-conky#10]
I noticed BL-Default.conkyrc puts a (nice looking) clock and calendar at the top.
However, the default tint2 config also has the time in the top RH corner and a pop-up calendar if you click it. We have some redundancy here.

For the default conky, maybe the clock and calendar could be taken out (and put in an alternative conky file) since the tint2 version takes up a lot less screen space?

Any thoughts?

**Comment by Sector11** [comment]
Easy ... 
`BL-Default.conkyrc` - same without Cal
`BL-Def-Cal.conkyrc` - what is now: `BL-Default.conkyrc`

Too easy ... I'm about to eat ... but will have it online shortly after.

**Comment by Sector11** [comment]
Done --- actually makes more sense.  :+1:
