### ISSUE TITLE
Add dependencies on conky and lua?

### ISSUE THREAD

**Issue by johnraff** [BunsenLabs/bunsen-conky#13]
Although conky is a default install in BunsenLabs maybe it would be polite to add a dependency on conky (conky-all?) to **bunsen-conky**, so people not using BunsenLabs can still install it. What's the minimum version number we should have? The Jessie version? Or even the Wheezy version if that's good enough?

Also, the lua scripts - what lua libraries do they need? Again, we ought to put the dependencies in this package.

**Comment by Sector11** [comment]
conly-all definitely. - let's not forget zenity. But I wouldn't make it a dependency.  What if someone with a few conkys running wants to try it... decided they don't like it ... it will remove conky-all and zenity?  So In the **README:**
`Required packages: conky-all, zenity (or yad - not in Jessie repos)`

Wheezy Package: conky-all (1.9.0-2)

```
dep: libc6 (>= 2.13) [s390x]
    GNU C Library: Shared libraries
    also a virtual package provided by libc6-udeb 
```

Jessie Package: conky-all (1.9.0-6)

```
dep: libc6 (>= 2.17)
    GNU C Library: Shared libraries
    also a virtual package provided by libc6-udeb 
```

I think you are going to have to use conky-all from jessie.  But if people want to use bunsen-conky shouldn't "their" system pick the `conky-all` version?  After all the conkys were developed on Wheezy and I tested all the zen scripts damo created on Jessie here as well

**Comment by johnraff** [comment]
As to versions, I just meant whether we should specify a _minimum_ version for the conkys to work. If they are known to work on Wheezy then I'll set it to 1.9.0-2. Of course Jessie users will get 1.9.0-6.

I don't think bunsen-conky itself needs zenity - that's the conky scripts in bunsen-utilities, which does have a dependency on zenity. 

bunsen-utilities is a _Recommend_ (not hard dependency)  of bunsen-conky because it's possible to use the conkys in bunsen-conky without the zenity scripts. I've just added bunsen-pipemenus to bunsen-conky's Recomends too, for the conky pipemenus. Recommends aren't compulsory, but they will come in with a normal install.

btw even if zenity had been made a hard dependency of bunsen-conky it wouldn't mean removing bunsen-conky would remove zenity too. If no other package depended on zenity, and the user hadn't installed it directly, it would become "auto-removable".

conky-all _has_ to be a dependency of bunsen-conky - without conky installed bunsen-conky would be meaningless!

**Comment by Sector11** [comment]
`conky-all has to be a dependency of bunsen-conky - without conky installed bunsen-conky would be meaningless!`

Never thought of it that way since I've had conky here since 2007 .. I guess it was a DUH moment.  :)

**Comment by johnraff** [comment]
Of course most BL users will already have conky installed, but adding it to the dependencies so installing bunsen-conky will automatically bring in conky-all is a sort of courtesy I guess...

**Comment by johnraff** [comment]
BTW who wrote the lua scripts? We should also put in dependencies on any lua libraries needed to run them.

**Comment by Sector11** [comment]
`Of course most BL users will already have conky installed, but adding it to the dependencies so installing bunsen-conky will automatically bring in conky-all is a sort of courtesy I guess...`

If they have manually installed "conky" they have `conky-std` this will bring in conky-all, a good thing, and if it is installed they will see a `conky-all is already the latest version` so yes, it's a nice courtesy 

conky-std supports:

```
X11, XDamage, XDBE, Xft, MPD, MOC, math, hddtemp, portmon, RSS, Weather, wireless, Imlib2, ALSA mixer, apcupsd.
I/O stats, argb, Lua and the cairo and imlib2 lua bindings, Audacious, and XMMS2
```

conky-all has all that plus:

```
IBM, nvidia, eve-online,
```

---

**LUA**

What ever #! came with and Bunsen has is enough for LUA to work in conky.  Doing an `aptitude search lua` on my machine the only thing installed is:  geany-plugin-lua and liblua5.1-0

damo tweaked the clock lua from and original done by llondonali1010 (Allison Pitt)
http://conky.pitstop.free.fr/wiki/index.php5?title=Air_clock_%28en%29
Credit is in the top 6 lines:

```
--[[
Analog Clock, based on code for Air Clock by Alison Pitt (2009)

Modified by <damo> April 2015

This clock is designed to look like KDE 4.3's "Air" clock, but from inside Conky.
```

---

The background lua script is based on her original (has a memory leak) that was tweaked by mrpeachy and dk75.  The built in calendar function is also mrpeachy's work.

Credit given in the top three lines:

```
--[[Background originally by londonali1010 (2009)
    ability to set any size for background mrpeachy 2011
    ability to set variables for bg in conkyrc dk75
```

Full use of the background function and the calendar are included in the first 76 lines of the script.  The blend of mrpeachy and dk75 on this are simply awesome work.
