### ISSUE TITLE
weather script

### ISSUE THREAD

**Issue by spiridonovmv** [BunsenLabs/bunsen-conky#14]
Function printf not accept numbers whith dot delimiters (37.57) in russian locales. 
Whith comma delimiters work fine.

I do this:
temperature=$(printf '%.0f' $(echo $weather | jq '.main.temp'| **tr '.' ','**))

**Comment by Sector11** [comment]
Will this work - please correct the Russian for me:

```
temperature=$(printf '%.0f' $(echo $weather | jq '.main.temp'))
# for Russian locales use - для российских локалей
# temperature=$(printf '%.0f' $(echo $weather | jq '.main.temp'| tr '.' ','))
```

Thank you for the tip.
Спасибо за совет.
Please excuse my net-translator.
