### ISSUE TITLE
Default Install - Reload Conky - Conky disappears

### ISSUE THREAD

**Issue by ghost** [BunsenLabs/bunsen-conky#15]
After a new install, Conky appeared centered. (Non-issue.)

Menu > Preferences > Conky > "Reload Conky"

Conky disappears. (_Does not return, left-top as expected._)

Menu > Preferences > Conky > "Conky Chooser"

Brings up a dialog, select the default for my profile at ~/.conkyrc

Check the box, close, re-run "Reload Conky" (from Menu>Pref>Conky) ... then Conky re-appears.

Seems a simple matter of setting the user's '.conkyrc' as the default upon first login. (_This is, of course, where a user would edit their respective '.*rc' file._)

**Comment by capn-damo** [comment]
On a default BL RC1 installation, the default conkyrc is "top right". Did the issue you describe occur at first boot, or after you have done something with the config?

> This is, of course, where a user would edit their respective '.*rc' file

`~/.conkyrc` is there as a default fallback. Alternative conky files are kept in `~/.config/conky/`

**Comment by ghost** [comment]
I meant "top right" (_my mistake_). -- Let me spin-up another VM from scratch and see the initial config scripts. This problem shouldn't be hard to fix.

**Comment by capn-damo** [comment]
Fixed: `Add test for sessionfile if restarting default conky`
https://github.com/BunsenLabs/bunsen-utilities/commit/6e646d35a4d75c7b2c9cb89121ba7083f3993523
