### ISSUE TITLE
characters codage on date time

### ISSUE THREAD

**Issue by serako** [BunsenLabs/bunsen-conky#16]
On fresh install RC1, the BL-Ellipses-Time.conkyrc don't have the good codage for the date caractere
I select in the debian installer the french language.

exemple:  i have "dA@cembre" (not exactly see pictures) normaly it's "décembre" .

![codage_error](https://cloud.githubusercontent.com/assets/16473922/12032530/7e3c1892-ae19-11e5-955f-b6961e7b9bbd.png)

my solution, it's add this line : override_utf8_locale yes

**Comment by Sector11** [comment]
^ edit three files
$HOME/.config/conky/BL-Ellipses-Time.conkyrc
$HOME/.config/conky/BL-Ellipses-Time-Blue.conkyrc
$HOME/.config/conky/BL-Ellipses-Time-Grey.conkyrc

No need to add a line, change:
`override_utf8_locale no`
to
`override_utf8_locale yes`

**Comment by johnraff** [comment]
@Sector11 should we make `override_utf8_locale yes` the default in all the conky config files? Or perhaps some of them?

**Comment by ghost** [comment]
I read that the switch forces UTF-8 regardless of the locale. When the switch is set, I imagine that locales using non-UTF8 encodings won't look very pretty. Tnky his might affect users using KOI (cyrillic-alphabet fonts), BIG (Chinese fonts), ISO8895 (different Latin alphabets), SHIFTJS etc pp badly. Why the hell doesn't conky get the font encoding right by itself?

**Comment by Sector11** [comment]
Can't answer that one Jens, but every conky I make since 2007 has had `override_utf8_locale yes` set because of problems people had showing the ° symbol mostly.  It fixed it in every instance that I know of.
Conky says:

```
override_utf8_locale    Force UTF8? requires XFT
```

And I have always used that IE:

```
xftfont Fantasque Sans Mono:bold:size=12
xftalpha 1.0
override_utf8_locale yes
```

All of the BL conkys I created use it.

**Comment by ghost** [comment]
Then let's set it.

**Comment by Sector11** [comment]
I can't - I've lost touch with GIT a long time ago.  I kept getting errors.  Someone else will have to do it.

I'm in advisory mode only.

**Comment by johnraff** [comment]
OK if it's cool with you @Sector11 I'll change those lines later next week.

**Comment by Sector11** [comment]
Awesome ... you just need to change the no to yes in three files.  :)

**Comment by johnraff** [comment]
OK now done.
There were five files that needed changing:
conky/BL-Ellipses-Time-Blue.conkyrc
conky/BL-Ellipses-Time-Grey.conkyrc
conky/BL-Ellipses-Time.conkyrc
conky/Classic.conkyrc
conky/conkyrc_cb
