### ISSUE TITLE
BL-Ellipses-Time

### ISSUE THREAD

**Issue by capn-damo** [BunsenLabs/bunsen-conky#7]
I noticed the conky placement is still set for twin monitors, so it appears top left of the right hand screen.

Maybe change alignment, gap_x and gap_y to something generic eg:

`alignment mm`
`gap_x 0`
`gap_y 0`

NB: `bunsen-utilities/bl-conkyzen` has been updated again.

**Comment by Sector11** [comment]
Done and online ... how we got all this done before John mad the DEB file.

**Comment by johnraff** [comment]
Hey, the .deb file gets built on-the-fly when someone runs the netinstall script, so the repo contents can be updated any time. There's no particular cutoff, at least right now.

That's the advantage of having the github repos in "source" format.

**Comment by capn-damo** [comment]
Cool - I didn't realize you could do that :)

**Comment by Sector11** [comment]
Ohhhhh that's a good one.

**Comment by johnraff** [comment]
The only downside is that the user using the current netinstall script installs a whole slew (~100MB?) of devscripts etc (it's done automatically by the script) and the install takes a lot longer than it will when we've got a proper Debian repo with normal deb files in it.

**Comment by Sector11** [comment]
Yea but ... always a but.  It is a test anyway and not 100% official ... or did I miss something?

**Comment by johnraff** [comment]
Sure it's a test, meant for people who'd like to help us out fixing glitches. 
...and for those who just can't wait for a taste of what BL will be like...

**Comment by Sector11** [comment]
Finally going to bite the bullet ... pick up a printer today ... print out instructions and kick this can tomorrow.

**Comment by johnraff** [comment]
Close this?

**Comment by capn-damo** [comment]
Yes :)
